name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_DEPLOY }}
        TARGET_REPO: Dlubal-Software/Dlubal_JavaScript_Library
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: npm install && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist
