name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@76-missing-descriptors-and-infos-in-javascript-command-library

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@76-missing-descriptors-and-infos-in-javascript-command-library
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Dlubal-Software/Dlubal_JavaScript_Library
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
